development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: photology_development
  pool: 5
  username: phadmin
  password: password
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: photology_test
  pool: 5
  username: phadmin
  password: password
  socket: /tmp/mysql.sock

production:
  DATABASE_URL: <%= ENV['CLEARDB_DATABASE_URL'] %>
