development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: photology_development
  pool: 5
  username: phadmin
  password: password
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: photology_test
  pool: 5
  username: phadmin
  password: password
  socket: /tmp/mysql.sock

production:
  url: <%= ENV['CLEARDB_DATABASE_URL'] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
