development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: photology_development
  pool: 5
  username: phadmin
  password: password
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: photology_test
  pool: 5
  username: phadmin
  password: password
  socket: /tmp/mysql.sock

production:
  CLEARDB_DATABASE_URL: <%= ENV['mysql2://b9f3c801638bc5:74ecee72@us-cdbr-iron-east-04.cleardb.net/heroku_6a6c4c916476655?reconnect=true'] %>
